"""Immutable pipeline state that flows through all agents."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Hypothesis:
    """A market hypothesis generated by the HypothesisAgent."""

    name: str
    rationale: str
    expected_type: str  # "momentum", "mean_reversion", "volume", "volatility", etc.


@dataclass(frozen=True)
class FactorCandidate:
    """A factor expression generated by the FactorAgent."""

    expression: str
    hypothesis_name: str
    rationale: str


@dataclass(frozen=True)
class FactorResult:
    """A factor candidate with its backtest metrics."""

    candidate: FactorCandidate
    ic_mean: float
    icir: float
    rank_ic_mean: float
    sharpe_ratio: float
    max_drawdown: float
    turnover: float
    alpha_decay: tuple[float, ...]


@dataclass(frozen=True)
class EvaluationDecision:
    """EvalAgent's verdict on the current iteration's results."""

    decision: str  # "accept", "reject", "refine"
    feedback: str
    suggestions: tuple[str, ...]
    best_factor: FactorResult | None


@dataclass(frozen=True)
class PipelineState:
    """Immutable state passed through the agent pipeline.

    Each agent receives the state and returns a new copy with updated fields.
    The orchestrator manages transitions and the feedback loop.
    """

    query: str
    iteration: int = 0
    max_iterations: int = 3

    hypotheses: tuple[Hypothesis, ...] = ()
    factors: tuple[FactorCandidate, ...] = ()
    results: tuple[FactorResult, ...] = ()
    evaluation: EvaluationDecision | None = None

    # Feedback from previous iterations (fed back to HypothesisAgent/FactorAgent)
    prior_feedback: str = ""

    # Accumulated across iterations
    all_results: tuple[FactorResult, ...] = ()

    # --- v2.0 Agent outputs (blueprint p3-4) ---
    research_summary: object = None   # ResearchSummary from ResearchSummaryAgent
    anomaly_report: object = None     # AnomalyReport from AnomalyDetectorAgent
    risk_advice: object = None        # RiskAdvice from RiskAdvisorAgent

    # Injected by orchestrator for new agents
    system_metrics: object = None     # Dict of service health metrics
    positions: object = None          # Current portfolio positions
    risk_metrics: object = None       # Current risk metrics dict

    def with_updates(self, **kwargs: object) -> PipelineState:
        """Create a new state with specified fields replaced."""
        current = {f.name: getattr(self, f.name) for f in self.__dataclass_fields__.values()}
        current.update(kwargs)
        return PipelineState(**current)
