"""HTML report generator — produces a self-contained report from pipeline results."""

from __future__ import annotations

import base64
import io
from datetime import datetime
from typing import TYPE_CHECKING

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402  (must come after backend selection)

from alpha_agent.pipeline.orchestrator import PipelineResult
from alpha_agent.pipeline.state import FactorResult

if TYPE_CHECKING:
    pass

# ---------------------------------------------------------------------------
# Jinja2-style template (rendered manually to avoid a dependency)
# We use str.format-style substitution with unique placeholders.
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Alpha Research Report</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: #f4f6f9;
    color: #1a1a2e;
    line-height: 1.6;
  }}
  header {{
    background: #1a1a2e;
    color: #e8eaf6;
    padding: 2rem 2.5rem;
    border-bottom: 4px solid #4fc3f7;
  }}
  header h1 {{ font-size: 1.75rem; font-weight: 700; margin-bottom: 0.4rem; }}
  header .meta {{ font-size: 0.9rem; opacity: 0.75; }}
  .container {{ max-width: 1100px; margin: 2rem auto; padding: 0 1.5rem; }}
  section {{ background: #fff; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.75rem;
             box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
  section h2 {{ font-size: 1.2rem; font-weight: 600; margin-bottom: 1rem;
                color: #1a1a2e; border-bottom: 2px solid #e0e0e0; padding-bottom: .5rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.875rem; }}
  th {{ background: #1a1a2e; color: #e8eaf6; padding: .55rem .75rem; text-align: left; }}
  tr:nth-child(even) {{ background: #f0f4ff; }}
  td {{ padding: .5rem .75rem; border-bottom: 1px solid #e8e8e8; }}
  .badge {{ display: inline-block; padding: .15rem .5rem; border-radius: 999px;
            font-size: .75rem; font-weight: 600; }}
  .badge-accept {{ background: #c8e6c9; color: #2e7d32; }}
  .badge-reject {{ background: #ffcdd2; color: #c62828; }}
  .badge-refine  {{ background: #fff9c4; color: #f57f17; }}
  .charts {{ display: flex; gap: 1.5rem; flex-wrap: wrap; }}
  .charts img {{ max-width: 100%; height: auto; border-radius: 6px;
                 box-shadow: 0 1px 3px rgba(0,0,0,.12); }}
  details {{ border: 1px solid #e0e0e0; border-radius: 6px; margin-bottom: .75rem; }}
  summary {{ padding: .65rem 1rem; cursor: pointer; font-weight: 600;
             background: #f5f7ff; border-radius: 6px; list-style: none; }}
  summary::-webkit-details-marker {{ display: none; }}
  summary::before {{ content: "▶  "; font-size: .75rem; color: #666; }}
  details[open] summary::before {{ content: "▼  "; }}
  .detail-body {{ padding: .75rem 1rem; font-size: .85rem; }}
  .detail-body pre {{ white-space: pre-wrap; word-break: break-word;
                       background: #f8f8f8; padding: .6rem; border-radius: 4px;
                       font-family: "SF Mono", Menlo, monospace; font-size: .8rem; }}
  .tag {{ display: inline-block; background: #e3f2fd; color: #1565c0;
          padding: .1rem .45rem; border-radius: 4px; font-size: .75rem; margin: .15rem; }}
  footer {{ text-align: center; color: #888; font-size: .8rem; padding: 1.5rem; }}
</style>
</head>
<body>
<header>
  <h1>Alpha Research Report</h1>
  <div class="meta">
    <span>Query: <strong>{query}</strong></span>&nbsp;&nbsp;|&nbsp;&nbsp;
    <span>Generated: {timestamp}</span>&nbsp;&nbsp;|&nbsp;&nbsp;
    <span>Iterations: {total_iterations}</span>
  </div>
</header>
<div class="container">

  <section>
    <h2>Factor Summary</h2>
    {summary_table}
  </section>

  <section>
    <h2>IC Mean by Factor</h2>
    <div class="charts">{ic_chart}</div>
  </section>

  <section>
    <h2>Alpha Decay (Best Factor)</h2>
    <div class="charts">{decay_chart}</div>
  </section>

  <section>
    <h2>Agent Thinking Log</h2>
    {thinking_log}
  </section>

</div>
<footer>Generated by AlphaAgent &mdash; {timestamp}</footer>
</body>
</html>
"""

_FORWARD_PERIODS = (1, 2, 3, 5, 10, 20)


# ---------------------------------------------------------------------------
# Generator class
# ---------------------------------------------------------------------------

class HTMLReportGenerator:
    """Generates a self-contained HTML report from pipeline results."""

    def generate(self, result: PipelineResult) -> str:
        """Return a complete, self-contained HTML string with embedded charts."""
        all_factors = list(result.accepted_factors) + list(result.rejected_factors)
        accepted_set = set(id(f) for f in result.accepted_factors)

        summary_table = self._build_summary_table(all_factors, accepted_set)
        ic_chart = self._build_ic_chart(all_factors)
        decay_chart = self._build_decay_chart(result)
        thinking_log = self._build_thinking_log(result)

        return _HTML_TEMPLATE.format(
            query=_escape(result.query),
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            total_iterations=result.total_iterations,
            summary_table=summary_table,
            ic_chart=ic_chart,
            decay_chart=decay_chart,
            thinking_log=thinking_log,
        )

    # ------------------------------------------------------------------
    # Summary table
    # ------------------------------------------------------------------

    def _build_summary_table(
        self, factors: list[FactorResult], accepted_ids: set[int]
    ) -> str:
        if not factors:
            return "<p>No factors evaluated.</p>"

        rows = []
        for fr in factors:
            decision = "accept" if id(fr) in accepted_ids else "reject"
            badge = f'<span class="badge badge-{decision}">{decision}</span>'
            decay_preview = (
                ", ".join(f"{v:.4f}" for v in fr.alpha_decay[:3]) + "…"
                if fr.alpha_decay
                else "—"
            )
            rows.append(
                f"<tr>"
                f"<td><code>{_escape(fr.candidate.expression)}</code></td>"
                f"<td>{fr.ic_mean:+.4f}</td>"
                f"<td>{fr.icir:+.4f}</td>"
                f"<td>{fr.rank_ic_mean:+.4f}</td>"
                f"<td>{fr.sharpe_ratio:+.4f}</td>"
                f"<td>{fr.turnover:.4f}</td>"
                f"<td>{decay_preview}</td>"
                f"<td>{badge}</td>"
                f"</tr>"
            )

        rows_html = "\n".join(rows)
        return f"""
<table>
  <thead>
    <tr>
      <th>Expression</th><th>IC Mean</th><th>ICIR</th><th>Rank IC</th>
      <th>Sharpe</th><th>Turnover</th><th>Decay (1/2/3d)</th><th>Decision</th>
    </tr>
  </thead>
  <tbody>{rows_html}</tbody>
</table>"""

    # ------------------------------------------------------------------
    # IC bar chart
    # ------------------------------------------------------------------

    def _build_ic_chart(self, factors: list[FactorResult]) -> str:
        if not factors:
            return "<p>No data.</p>"

        labels = [f"F{i+1}" for i in range(len(factors))]
        values = [fr.ic_mean for fr in factors]
        colors = ["#4caf50" if v >= 0 else "#f44336" for v in values]

        fig, ax = plt.subplots(figsize=(max(6, len(factors) * 0.8), 4))
        bars = ax.bar(labels, values, color=colors, edgecolor="white", linewidth=0.5)
        ax.axhline(0, color="#333", linewidth=0.8, linestyle="--")
        ax.set_title("IC Mean by Factor", fontsize=12, fontweight="bold")
        ax.set_ylabel("IC Mean")
        ax.set_xlabel("Factor")
        ax.tick_params(axis="x", rotation=45)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

        # Value labels on bars
        for bar, val in zip(bars, values):
            y = bar.get_height()
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                y + (0.001 if y >= 0 else -0.003),
                f"{val:+.4f}",
                ha="center",
                va="bottom" if y >= 0 else "top",
                fontsize=7,
            )

        fig.tight_layout()
        img_b64 = _fig_to_base64(fig)
        plt.close(fig)
        return f'<img src="data:image/png;base64,{img_b64}" alt="IC chart">'

    # ------------------------------------------------------------------
    # Alpha decay line chart
    # ------------------------------------------------------------------

    def _build_decay_chart(self, result: PipelineResult) -> str:
        best = _pick_best_factor(result)
        if best is None or not best.alpha_decay:
            return "<p>No alpha decay data available.</p>"

        periods = list(_FORWARD_PERIODS[: len(best.alpha_decay)])
        decay = list(best.alpha_decay[: len(periods)])

        fig, ax = plt.subplots(figsize=(7, 4))
        ax.plot(periods, decay, marker="o", color="#1565c0", linewidth=2, markersize=6)
        ax.fill_between(periods, decay, alpha=0.15, color="#1565c0")
        ax.axhline(0, color="#333", linewidth=0.8, linestyle="--")
        ax.set_title(
            f"Alpha Decay — {_escape(best.candidate.expression[:60])}",
            fontsize=11,
            fontweight="bold",
        )
        ax.set_xlabel("Forward Period (days)")
        ax.set_ylabel("IC Mean")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        fig.tight_layout()
        img_b64 = _fig_to_base64(fig)
        plt.close(fig)
        return f'<img src="data:image/png;base64,{img_b64}" alt="Alpha decay chart">'

    # ------------------------------------------------------------------
    # Thinking log (collapsible per iteration)
    # ------------------------------------------------------------------

    def _build_thinking_log(self, result: PipelineResult) -> str:
        if not result.all_states:
            return "<p>No iteration data recorded.</p>"

        sections = []
        for i, state in enumerate(result.all_states, start=1):
            hyp_tags = "".join(
                f'<span class="tag">{_escape(h.name)}</span>'
                for h in state.hypotheses
            )
            factor_items = "".join(
                f"<li><code>{_escape(fc.expression)}</code> — {_escape(fc.rationale)}</li>"
                for fc in state.factors
            )
            decision_html = ""
            if state.evaluation:
                ev = state.evaluation
                badge_cls = f"badge-{ev.decision}"
                decision_html = (
                    f'<p><strong>Decision:</strong> '
                    f'<span class="badge {badge_cls}">{_escape(ev.decision)}</span></p>'
                    f"<p><strong>Feedback:</strong> {_escape(ev.feedback)}</p>"
                )
                if ev.suggestions:
                    sugg_items = "".join(
                        f"<li>{_escape(s)}</li>" for s in ev.suggestions
                    )
                    decision_html += f"<p><strong>Suggestions:</strong><ul>{sugg_items}</ul></p>"

            body = (
                f"<div class='detail-body'>"
                f"<p><strong>Hypotheses:</strong> {hyp_tags or '—'}</p>"
                f"<p><strong>Factors generated:</strong></p><ul>{factor_items or '<li>None</li>'}</ul>"
                f"{decision_html}"
                f"</div>"
            )
            sections.append(
                f"<details><summary>Iteration {i}</summary>{body}</details>"
            )

        return "\n".join(sections)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _escape(text: str) -> str:
    """Minimal HTML escaping for safe embedding in HTML."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _fig_to_base64(fig: plt.Figure) -> str:
    """Render a matplotlib figure to a base64-encoded PNG string."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("ascii")


def _pick_best_factor(result: PipelineResult) -> FactorResult | None:
    """Return the accepted factor with highest IC, or the best rejected factor."""
    candidates: list[FactorResult] = list(result.accepted_factors) or list(result.rejected_factors)
    if not candidates:
        return None
    return max(candidates, key=lambda fr: fr.ic_mean)
