/** Maintained product guidance, not a live performance or account-status feed. */
export type Copy = readonly [zh: string, en: string];
export interface GuideEntry {
  id: string;
  title: Copy;
  body: Copy;
  steps?: readonly Copy[];
  href?: string;
  link?: Copy;
}
export interface GuideChapter { id: string; title: Copy; entries: readonly GuideEntry[] }
export const GUIDE_VERSION = "2026-09-08";
export const GUIDE: readonly GuideChapter[] = [
  { id: "start", title: ["开始与收益边界", "Start & income"], entries: [
    { id: "purpose", title: ["它能帮你做什么？", "What is this tool for?"], body: ["Alpha Agent 是研究、证据核对与模拟验证工作台，不是自动赚钱系统。工程修复让记录更可靠，但目前仍缺少足够长、同策略、扣成本的完整前瞻证据，不能据此认定实盘有超额收益。", "Alpha Agent supports research, evidence review and paper validation. Engineering reliability does not establish investment skill. A sufficiently long, complete, same-policy, cost-adjusted forward record is still missing."], steps: [["普通投资者先用今日推荐、股票详情、投资计划、研究记录和模拟仓；无需先学会编写因子。", "Investors can start with Picks, stock details, the investment plan, notebook and paper accounts. Writing factors is optional."], ["收益、研究报酬和节省时间是三件事。分别记录，别用平台积分代替现金收入。", "Investment returns, research compensation and time saved are different outcomes. Track them separately; points are not cash."]] },
    { id: "investing-income", title: ["路径一：辅助个人投资", "Path 1: support your investing"], body: ["真正收益来自你在券商账户承担风险后的净结果，平台不连接券商、不执行真实订单。现阶段更适合帮助你排除坏交易、解释持仓和积累前瞻记录，而不是照买榜单。", "Real investment results arise in your brokerage account, with capital at risk. This platform neither connects to a broker nor executes live orders. Use it to reject weak trades, understand holdings and build a forward record, not to copy a ranking."], steps: [["事先写清期限、能承受的损失、仓位与复查规则；不使用生活必需资金或借贷资金做平台试验。", "Write down your horizon, loss tolerance, position limits and review rules before testing. Do not use essential living funds or borrowed money for platform experiments."], ["先模拟，固定政策、成本和基准。多个重叠的 5 日或 60 日窗口不是多个独立样本。", "Start on paper with a fixed policy, costs and benchmark. Overlapping 5-day or 60-day windows are not independent observations."], ["只有证据足够、账本完整且风险可接受时，才自行考虑是否值得小范围实盘验证。没有适合所有人的通过天数或保证盈利的分数线。", "Only consider a limited live test if evidence, record completeness and risk are acceptable. There is no universal number of days or score that guarantees profitability."]], href: "/picks", link: ["打开今日推荐", "Open Picks"] },
    { id: "brain-income", title: ["路径二：BRAIN 研究顾问报酬", "Path 2: BRAIN research compensation"], body: ["这是与股票实盘盈亏不同的路径。WorldQuant 官方提供按研究创意质量获得报酬的机会；实际资格、接纳与付款以你的正式顾问状态、合同和官方记录为准。本平台不核定报酬，也不保证每个通过的 alpha 都带来收入。", "This is separate from live stock returns. WorldQuant offers the opportunity to earn compensation for research ideas. Eligibility, acceptance and payment depend on your official status, agreement and records. This app does not determine compensation or guarantee income per passing alpha."], steps: [["先在官方确认顾问 onboarding 已完成。面试通过或 Workday 没有待办，本身不等于付款资格已生效。", "Confirm completed onboarding with WorldQuant. Passing an interview or an empty Workday task list does not by itself confirm active payment eligibility."], ["在本平台研究和仿真，在官方核对所有 submission checks、提交状态与权益。不要把本地 GOOD、入库或仿真完成当作官方接纳。", "Research and simulate here, then verify submission checks, submission status and entitlements on BRAIN. Local GOOD ratings, storage and completed simulations are not official acceptance."], ["用实际收到的报酬减去模型、数据和运行费用，并记录研究工时，评估这条路径是否值得继续。", "Track actual compensation received minus model, data and execution costs, alongside research hours."]], href: "https://worldquantbrain.com/consultant", link: ["官方顾问计划说明", "Official consultant program"] },
    { id: "setup", title: ["第一次使用：完成四件事", "First visit: four steps"], body: ["普通浏览不需要额外运行模型。只有需要 LLM 解释或 BRAIN 挖掘时，才配置对应凭据；不要把密钥填进研究记录或截图。", "Browsing does not require a new model run. Configure credentials only for LLM assistance or BRAIN mining, and never put keys in notes or screenshots."], steps: [["登录，核对当前账户。到设置中保存自己的 LLM/BRAIN 凭据，并用对应连接检查确认可用。", "Sign in and verify your account. Save your own LLM/BRAIN credentials in Settings and use the relevant connection check."], ["在今日推荐展开“我的投资计划”，录入真实持仓权重与日期、自设上限和复查频率。未分配比例不自动视为现金。", "Expand My investment plan in Picks. Enter actual holding weights, their date, your limits and review cadence. Unallocated weight is not assumed to be cash."], ["确认数据日期、市场日和策略。战术 5 日与战略 60 日分开比较，不混用置信度或绩效。", "Check data date, market session and policy. Compare tactical 5-day and strategic 60-day policies separately."], ["为首个关注标的记录理由、反证、失效条件、来源与复查日期。先观察也是有效决定。", "For a first watch candidate, record rationale, counterevidence, invalidation, sources and review date. Watching without acting is valid."]], href: "/settings", link: ["打开设置", "Open Settings"] },
  ] },
  { id: "routine", title: ["日常决策流程", "Decision routine"], entries: [
    { id: "weekly", title: ["每周一次：先检查，再决定", "Weekly: inspect before deciding"], body: ["以下是一个可调整的使用节奏，不是强制调仓规则。不要因为页面每天有新排名，就每天换仓。", "This is an adjustable review routine, not a mandatory rebalance rule. Daily changes in rank do not require daily trading."], steps: [["看数据页和警报：是否有过期快照、任务失败、缺价格或影响现有持仓的新信息？有硬缺口时暂停新动作。", "Review Data and Alerts for stale snapshots, failed jobs, missing prices or information affecting holdings. Pause new actions when essential evidence is missing."], ["核对投资计划与当前持仓，再从推荐中选少量值得深入研究的候选；分数高不代表适合你的组合。", "Update your plan and holdings before choosing a small research shortlist from Picks. A high score does not establish portfolio fit."], ["打开股票详情，看来源时间、信号归因与反向证据。Rich Brief 是解释助手，涉及事实必须打开原始来源核实。", "Inspect stock details, source dates, attribution and contrary evidence. Rich Brief is an explanation aid; verify factual claims against primary sources."], ["更新研究记录，只在原有论点、估值或风险条件发生实质变化时考虑动作。用模拟仓检查成本和组合影响。", "Update the notebook. Consider action only when the thesis, valuation or risk conditions materially change; inspect costs and portfolio effects on paper."], ["复查策略绑定的净收益、回撤、换手、基准与异常。保留不操作、继续观察和证据不足的结论。", "Review policy-bound net returns, drawdown, turnover, benchmarks and exceptions. Retain no-action, watch and insufficient-evidence decisions."]], href: "/alerts", link: ["查看警报", "Review Alerts"] },
    { id: "policy", title: ["怎样读今日推荐", "How to read Picks"], body: ["排名是相对信号排序，不是预期收益率、仓位比例或实时买卖指令。战术 5 日与战略 60 日是不同信号政策，不表示到第 5/60 天必定卖出。做空榜仅供研究，不能直接套用做多账户的收益或忽略借券成本。", "Ranks are relative signal scores, not expected returns, position sizes or live orders. Tactical 5-day and strategic 60-day are distinct signal policies, not automatic exit dates. A short ranking is research only; long-account returns and costs do not validate short trades."], href: "/picks", link: ["查看推荐与政策说明", "Review Picks and policy notes"] },
    { id: "paper", title: ["怎样用模拟仓", "How to use paper accounts"], body: ["区分自己的手动模拟账户与自动跟随策略的验证账户。下单不等于成交，成交不等于盈利。先查订单状态、实际价格日期、费用、未成交原因，再看净值。模拟成交按既定交易日收盘规则，不模拟完整的盘中流动性。", "Distinguish your manual paper account from automated policy-validation accounts. An order is not a fill, and a fill is not a profit. Check order state, price date, costs and unfilled reasons before NAV. Closing-session execution does not model full intraday liquidity."], steps: [["账户估值截至日期不等于今天；连续策略账本当前仍主要在调仓日估值，不能拿它当每日实时风险监控。", "Valuation date is not necessarily today. Continuous policy books are still primarily marked on rebalance dates, not a live daily risk feed."], ["发现历史缺口，不要重置账户来美化曲线；保留异常并对新版本另起可追踪验证记录。", "Do not reset accounts to improve a chart when history has gaps. Retain exceptions and separately track new policy versions."]], href: "/paper", link: ["打开模拟仓", "Open Paper"] },
    { id: "thesis", title: ["一条可复查的投资论点", "A reviewable thesis"], body: ["示例仅说明写法，不推荐具体股票：我关注公司 A，因为已披露的经营现金流改善；反证是应收账款增速高于收入；下一份财报复查。若现金转化继续恶化，则重新评估原论点，而不是用新故事解释每一次下跌。", "Writing example, not a stock recommendation: I watch company A because reported operating cash flow improved; the counterargument is receivables growing faster than revenue; review the next report. Deteriorating cash conversion would challenge the thesis instead of inviting a new story for every price decline."], steps: [["来源栏记原始链接和日期，失效条件尽量可核对。平台只保存记录，不自动核实事实或执行止损。", "Record primary links and dates; make invalidation observable. The app stores notes but does not independently verify facts or execute stop losses."], ["目前每个股票保留最新一份记录，最多 30 个股票；复查日期会提示到期，但不会自动发通知。", "Currently one latest note per ticker, up to 30 tickers. Due dates are displayed, not automatic notifications."]] },
    { id: "baseline", title: ["每月一次：和简单替代方案比较", "Monthly: compare simple alternatives"], body: ["在“跟随这套策略，结果怎样？”中打开只读对照，比较原始目标、月度目标、免调仓带、SPY、RSP 与现金。同区间、同成本口径才有意义。现金不计利息；ETF 对照不含完整分红税费，名称不是购买推荐。", "Open the read-only comparison under policy evidence: recorded targets, monthly targets, a no-trade band, SPY, RSP and cash. Use matched intervals and costs. Cash excludes interest; ETF comparisons omit full dividends and taxes and are not purchase recommendations."], steps: [["回放使用过去已记录的目标，月度只用当月首个可用目标，不是重建完整月初选股策略。", "Replay uses recorded targets. Monthly uses the first available target in a month, not a reconstructed month-start selection strategy."], ["不要挑最高收益列立即上线。记录假设，另做前瞻验证；降低换手可能降低成本，也可能错过机会。", "Do not deploy the highest-return column. Record a hypothesis and test it forward; less turnover may lower costs or miss opportunities."]] },
  ] },
  { id: "research", title: ["因子与 BRAIN", "Factors & BRAIN"], entries: [
    { id: "local-research", title: ["本地因子研究的完整路径", "Local factor research path"], body: ["因子 Alpha → 翻译/编辑表达式 → 回测 → 因子库 → 选股 → 报告。先提出经济机制，再用数据验证；调整参数后直接重测表达式，不必重复让 LLM 翻译。", "Alpha → translate/edit expression → Backtest → Factor Zoo → Screener → Report. Start with an economic mechanism and test it. After changing parameters, rerun the expression without retranslating it."], steps: [["先看字段覆盖、时间可用性和样本外表现，再看 Sharpe。缺失持仓或运营明细时先看页面原因与返回明细选项。", "Check field coverage, point-in-time availability and out-of-sample results before Sharpe. Use the stated reason and detail-return option for missing holdings or operations panels."], ["一次只改少量假设，保留失败试验。挑选过的历史最佳结果会受到多重试验与过拟合影响。", "Change few assumptions at a time and retain failed trials. Selecting historical winners introduces multiple-testing and overfitting risk."], ["本地字段、运算符和 BRAIN Fast Expression 不是完全相同的执行环境，表达式不能默认直接互通。", "Local fields/operators and BRAIN Fast Expression are different execution environments. Expressions are not automatically portable."]], href: "/alpha", link: ["打开因子研究", "Open Alpha"] },
    { id: "mining", title: ["BRAIN 一轮挖掘到底经历什么", "What happens in a BRAIN run?"], body: ["生成候选 → LLM 逻辑预筛与规则证据筛选 → 按预算入选 → GitHub Actions 执行官方仿真 → 保存结果 → 查询可用的官方检查。仿真完成与正式提交 alpha 是不同阶段，最终以 BRAIN 官方状态为准。", "Generate candidates → LLM and deterministic evidence screening → budgeted selection → official simulation through GitHub Actions → persist results → retrieve available official checks. Completed simulation and formal alpha submission are different stages; official BRAIN status is authoritative."], steps: [["生成池是计划生成供筛选的候选数量；仿真预算是最多送去真实仿真的数量，不承诺生成或通过同样多的因子。", "The generation pool is the target number of screening candidates. The simulation budget caps actual simulations, not guaranteed generated or passing results."], ["选准 RUN，打开候选审计/全部候选，查看未入选表达式、字段证据、LLM 状态、分数和原因；再看已仿真结果。", "Select the correct RUN and open Candidate audit / All candidates to inspect rejected expressions, field evidence, LLM state, scores and reasons before reviewing simulations."], ["0 条入选时先区分证据不足与调度/鉴权故障，不能用不断扩大预算来解决前置技术失败。", "For zero selections, distinguish weak evidence from dispatch/auth failures. Increasing the budget does not fix an upstream technical failure."], ["复用 RUN 是复用其配置开始新研究，不要把新旧 RUN、全部候选和通过筛选后的结果数量混为一谈。", "Reusing a RUN starts research from its settings. Do not confuse runs, all candidates and filtered result counts."]], href: "/brain", link: ["打开 BRAIN 挖掘", "Open BRAIN mining"] },
    { id: "correlation", title: ["GOOD 为何仍不能提交？", "Why can GOOD still fail?"], body: ["GOOD/EXCL 是绩效分层，不代表所有官方检查通过。Self-correlation 衡量与既有 alpha 收益表现的相似性，不是单只股票价格的时间自相关。官方阈值与检查结果以该 alpha 页面为准；本项目通常按 0.70 核对。", "GOOD/EXCL describe performance tiers, not all submission checks. Self-correlation concerns similarity to existing alpha performance, not a stock price autocorrelation. The alpha's official checks are authoritative; this project normally checks against 0.70."], steps: [["本地约 0.65 的去重门槛是搜索与预算策略，不会直接修改已仿真因子的收益，但会改变哪些候选获得仿真机会，也可能排除有用候选。", "The roughly 0.65 local deduplication threshold is a search/budget rule. It does not alter a simulated alpha's return series but changes who receives simulation capacity and may exclude useful ideas."], ["未执行、等待、查询失败与数值超限分别处理。代理相关性 S-CORR* 不能替代官方 S-CORR，缺值也不等于通过。", "Treat not-executed, pending, query-failed and threshold-failed separately. Proxy S-CORR* cannot replace official S-CORR; missing is not passing."], ["高相关时改变经济信息来源与机制，并验证其有效性；单纯换窗口、嵌套运算符或凑复杂度不保证降低真实相关。", "Investigate new information sources and mechanisms, then validate them. Changing windows or adding nested operators does not guarantee lower realized correlation."]] },
    { id: "research-tools", title: ["其它研究模块什么时候用", "When to use the other research tools"], body: ["选股用于在明确条件下缩小研究范围，因子库用于保存可复现资产，报告用于比较结果。演化监控查看衰减、提案和变更账本；全局策略启用与批准只限管理员。普通用户不需要每天打开这些工具。", "Screener narrows a research universe, Factor Zoo stores reproducible assets and Reports compare results. Evolution tracks decay, proposals and change history; global activation/approval is admin-only. Investors need not visit every tool daily."], href: "/methodology", link: ["查看字段、运算符与方法论", "Read fields, operators and methodology"] },
  ] },
  { id: "metrics", title: ["指标怎么读", "Metric meanings"], entries: [
    { id: "hit-rate", title: ["方向一致度，不是盈利概率", "Direction agreement is not profit probability"], body: ["“1日/近1月”通常表示按 1 个交易日评价方向、统计最近约 1 个月的历史，不是预测未来 1 个月。更长窗口必须等待结果成熟，且样本会重叠。命中率高可能仍亏损，因为亏损幅度、成本与市场普涨基线同样重要。", "“1D / past month” generally evaluates a one-session direction over a recent month of history, not a one-month forecast. Longer outcome windows need maturity and overlap. High agreement can still lose money because loss size, costs and a rising-market baseline matter."], steps: [["示例：10 次各赚 1 元、1 次亏 20 元，命中率约 91%，但未计费用已亏 10 元。", "Example: ten gains of 1 and one loss of 20 give about 91% wins but a net loss of 10 before costs."], ["不要为了数字好看事后改成 2 日或 3 日。先固定预测问题与持有窗口，再比较同样本、同基准下的净效果。", "Do not change to two or three days after seeing nicer numbers. Define the question and horizon first, then compare matched samples and benchmarks."]] },
    { id: "returns", title: ["净收益、超额收益与回撤", "Net return, excess return and drawdown"], body: ["净收益是按页面列明成本扣除后的结果，超额收益是相同区间相对基准的差。两者都可能为负。最大回撤描述已观测的峰谷损失，不是未来最大可能损失；只在调仓日估值的曲线会漏掉盘中及日间风险。", "Net return deducts the costs stated on the page; excess return compares the same interval to a benchmark. Both may be negative. Drawdown is an observed peak-to-trough loss, not a cap on future loss. Rebalance-only valuations miss intraday and between-rebalance risk."], steps: [["账户累计收益含首次建仓成本；账本横向比较从首次成交收盘开始，不含这笔成本。只读回放另从现金开始并计首次建仓成本。不要混算。", "Account return includes entry costs; the ledger's matched comparison starts at the first filled close and excludes that initial cost. Replay starts from cash and includes entry costs. Do not mix these bases."]] },
    { id: "technical", title: ["IC、Sharpe、Fitness 与换手", "IC, Sharpe, Fitness and turnover"], body: ["IC 衡量因子排序与后续收益排序的相关性；IC OOS 是样本外结果。Sharpe 衡量平均收益相对于波动的大小，不保证尾部安全。Fitness 是 BRAIN 的综合绩效指标，应看官方定义。换手反映交易负担，双边与单边口径必须一致。", "IC measures association between factor ranks and forward return ranks; IC OOS refers to out-of-sample results. Sharpe scales average return by volatility, not tail safety. Fitness is a BRAIN composite metric; consult its official definition. Turnover measures trading load; match one-way or two-way conventions."], steps: [["Folds 是验证分段，不是独立盈利次数。DS 等缩写请先查看该处说明，不同页面的评分不能只看数值横比。", "Folds are validation partitions, not independent profitable trades. Read local definitions for DS and other abbreviations; scores across pages may not be comparable."]] },
    { id: "missing", title: ["雷达图缺测与数据新鲜度", "Radar gaps and data freshness"], body: ["股票雷达固定六个维度。无分数的轴保留但不填零；零权重也不意味着该维度不存在。快照有效表示满足发布与时效规则，不代表每个底层数据源都刚更新，更不是交易机会已获证明。", "Stock radar retains six dimensions. Missing scores stay missing rather than zero; zero weight does not erase a dimension. A valid snapshot satisfies publication/freshness rules, not simultaneous freshness of every source or proof of an opportunity."], href: "/data", link: ["检查数据源与任务链", "Check sources and jobs"] },
  ] },
  { id: "recovery", title: ["故障与恢复", "Troubleshooting"], entries: [
    { id: "llm", title: ["LLM 超时、失败或没有生成", "LLM timeout, failure or no output"], body: ["先检查登录、所选 provider、官方入口、模型名称与自己的 Key。Kimi 等推理模型可能需要较长时间；超时是技术状态，不是因子经济逻辑低质的证据。不要为了绕过问题盲目更换模型或反复点击。", "First check sign-in, provider, official endpoint, model name and your key. Reasoning models such as Kimi may take time; a timeout is a technical state, not evidence of a weak economic idea. Avoid blind model changes or repeated clicks."], steps: [["BRAIN 的 LLM 筛选失败后可能转规则证据筛选；保留的评分仍有效，未评分候选不应被叫作官方回测失败。", "A failed BRAIN LLM screen may fall back to deterministic evidence. Retained scores remain usable; unscored candidates are not failed official simulations."], ["记录模块、时间、RUN/request ID、错误类别与是否可复现；不发送密钥。恢复后只重试必要阶段，避免重复消耗预算。", "Record module, time, RUN/request ID, error class and reproducibility, without keys. Retry only necessary stages after recovery to avoid duplicate spend."]], href: "/settings", link: ["检查模型与凭据", "Check model and credentials"] },
    { id: "dispatch", title: ["GitHub 401/422、502 与零结果", "GitHub 401/422, 502 and zero results"], body: ["GitHub 401 通常指派遣凭据失效，disabled workflow 的 422 指任务未启用；HTTP 502 还需看内部错误。它们不说明 alpha 质量差。若候选已生成但 0 入选，查看逐条筛选原因；若已仿真却看不到结果，先核对 RUN、状态/家族筛选与分页。", "GitHub 401 usually indicates invalid dispatch credentials; a disabled-workflow 422 means the job is disabled. Inspect the underlying cause of a 502. None establishes poor alpha quality. For generated but unselected candidates, inspect decisions; for missing simulated results, check RUN, filters and pagination."], href: "/brain", link: ["查看本轮审计", "Inspect run audit"] },
    { id: "stale", title: ["刷新后仍旧过期，怎么办？", "Still stale after refresh?"], body: ["页面刷新、数据任务完成、推荐快照发布、模拟订单成交和净值估值是不同阶段。先看数据页哪一步未完成，再看对应时间戳。不要用浏览器刷新时间冒充信号计算时间，或在旧快照上继续下单。", "Page refresh, data-job completion, snapshot publication, paper fills and valuation are separate stages. Check which stage is incomplete and its timestamp. A browser refresh time is not signal computation time; do not act on an obsolete snapshot."], steps: [["401 先登录；403 表示权限不足，不要重试管理员操作；429 按提示等待。数据库额度问题由管理员核对控制台，不能假设每次都是额度耗尽。", "Sign in for 401; 403 means insufficient permission, not a reason to retry admin actions; respect 429 backoff. Database quotas need an admin console check, not an automatic diagnosis."], ["已有研究、模拟仓和 BRAIN 记录不要为排错随意删除；暂停新动作通常比重置历史更安全。", "Do not delete research, paper history or BRAIN records to troubleshoot. Pausing new actions is usually safer than resetting history."]], href: "/data", link: ["打开数据健康状态", "Open data health"] },
  ] },
  { id: "changes", title: ["已优化与未完成", "Delivered & remaining"], entries: [
    { id: "delivered", title: ["主要优化一览", "Main improvements"], body: ["已落地的主线是让数据、决策和记录更一致，而非增加一个“必胜信号”。", "The main goal has been consistent data, decisions and records, not a supposedly unbeatable signal."], steps: [["统一 Design System：生产控件、字号、图表、六维雷达、状态和中英说明；新手册也复用同一套组件。", "Standardized production controls, typography, charts, six-axis radar, states and bilingual guidance. This guide reuses the same system."], ["修复 LLM 路径、凭据与失败反馈；BRAIN 按 RUN 留存候选、筛选证据和官方检查状态，不再只显示成功结果。", "Repaired LLM paths, credential handling and failure feedback. BRAIN retains run-specific candidates, screening evidence and official-check states rather than only successes."], ["推荐冻结快照和策略绑定，模拟执行按真实交易日收盘判断；历史异常不删除，收益口径分开解释。", "Bound recommendations to snapshots and policies; paper execution uses real exchange closes. Historical exceptions are retained and return bases are explicit."], ["新增私人投资计划、集中度复查、投资论点和低换手基准对照；管理操作限管理员。", "Added private plans, concentration review, theses and low-turnover benchmark comparisons, with global administration restricted."], ["后端连接池创建加锁与限额、健康与演化查询批量化、减少重复行情写入和索引、保留证据后再清理原始信号。", "Bounded and locked backend pool creation; batched health/evolution queries; reduced duplicate quote writes/indexes; raw signals are pruned only after evidence materialization."]] },
    { id: "limits", title: ["当前不要误以为已完成的能力", "Capabilities not yet complete"], body: ["尚未完成：连续账户每日盯市、ETF 穿透、真实账户回撤监测、候选组合适配排序、论点修订历史与事件自动核实。没有真实券商执行、保证盈利、自动确认顾问收入或完整税后总回报。", "Not complete: daily marks for continuous books, ETF look-through, real-account drawdown monitoring, portfolio-fit ranking, thesis version history and automatic event verification. There is no live brokerage execution, guaranteed profit, compensation confirmation or complete after-tax total-return accounting."], steps: [["手册是截至版本日期的功能说明，不是实时服务状态。异常以数据页、运行记录和官方页面为准。", "This guide describes capabilities as of its version date, not live service status. Check Data, run records and official pages for current issues."], ["已增加 Node 同进程连接池复用、API 连接等待上限、有容量限制的缓存、公共低换手对照的重复请求合并及接口耗时记录。它们减少资源浪费，但不代表每次请求都会更快；尚未取得长期延迟分布。", "Shared process-local Node pools, bounded API connection waits and caches, duplicate-read coalescing for the public turnover study, and request timings are available. They reduce wasted resources but do not make every request faster; long-term latency distributions have not yet been measured."], ["信号查询已只读取必要字段，但历史 JSON 冷热分层、归档迁移和物理空间回收尚未执行。未删除研究记录，也未付费扩容。", "Signal queries now read only required envelope fields. Hot/cold storage, archive migration and physical space reclamation remain unimplemented. Research records have not been deleted, and no paid capacity upgrade was made."]] },
  ] },
];

export const GUIDE_SOURCES = [
  { href: "https://worldquantbrain.com/consultant", label: ["WorldQuant：顾问计划与报酬机会", "WorldQuant: consultant program and compensation opportunity"] as Copy },
  { href: "https://www.investor.gov/introduction-investing/getting-started/understanding-fees", label: ["Investor.gov：费用如何影响收益", "Investor.gov: understanding fees"] as Copy },
  { href: "https://www.investor.gov/introduction-investing/getting-started/asset-allocation", label: ["Investor.gov：资产配置与分散风险", "Investor.gov: asset allocation and diversification"] as Copy },
];
