"""Generate alpha_agent/core/brain_registry.py from /tmp/brain_source_of_truth.json.

Source of truth is the Feishu/Lark Bitable consolidated into JSON by the
upstream `dump_feishu_brain.py` tool. This script is idempotent and
deterministic — re-running it on the same JSON produces byte-identical
output (modulo dict key order, which we sort).

Run: python3 scripts/build_brain_registry.py
Output: alpha_agent/core/brain_registry.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from textwrap import dedent

SOURCE = Path("/tmp/brain_source_of_truth.json")
OUT = Path(__file__).resolve().parents[1] / "alpha_agent" / "core" / "brain_registry.py"

# Which data-field categories are in the B+ whitelist.
# Categories EXCLUDED (for future Option A expansion): News, Options, SocialMedia
B_PLUS_CATEGORIES = {"PriceVolume", "Fundamental", "Model", "Analyst", "Sentiment"}

# Model sub-filter: keep derivable-from-public-data fields; skip WQ-proprietary `mdl77_*`
MODEL_PROPRIETARY_PREFIX = "mdl77_"

# Data source routing per category (informational; consumed by future loader layer)
DATA_SOURCE_BY_CATEGORY = {
    "PriceVolume": "yfinance",
    "Fundamental": "edgar",
    "Model": "local_compute",
    "Analyst": "finnhub",
    "Sentiment": "finnhub",
}

# Operators that have a working vectorized implementation today or will have one
# after this PR. Everything else is registered but raises NotImplementedError at
# execution time (keeps the LLM whitelist accurate; execution layer guards scope).
IMPLEMENTED_OPERATORS = frozenset({
    # Existing (15)
    "ts_mean", "ts_rank", "ts_corr", "ts_std", "ts_zscore",
    "rank", "scale", "log", "sign", "winsorize",
    "divide", "subtract", "multiply", "add", "power",
    # New in this PR (~14)
    "ts_delta", "ts_delay", "ts_sum", "ts_product",
    "abs", "sqrt", "inverse", "zscore", "if_else",
    "max", "min", "is_nan", "reverse", "signed_power",
})

OP_NAME_RE = re.compile(r"^([a-z_][a-z_0-9]*)\s*\(")

# BRAIN operators that cannot be called as Python functions and must be written
# as native Python syntax (comparison, boolean, unary). AST relaxation in
# factor_ast.py (ast.Compare / ast.BoolOp / ast.UnaryOp) handles these;
# they are NOT registered as callable operator names.
SYNTACTIC_ONLY_OP_NAMES = frozenset({"and", "or", "not"})


def parse_op_name(signature: str) -> str | None:
    """Extract canonical operator name from a BRAIN signature like 'ts_mean(x, d)'.

    Returns None for infix-only signatures (e.g., 'input1 < input2') — those
    are handled by the AST layer directly, not the callable-operator registry.
    """
    m = OP_NAME_RE.match(signature.strip())
    if not m:
        return None
    return m.group(1)


def py_repr(s: str) -> str:
    """Deterministic Python string literal, safe for embedding."""
    return repr(s)


def build() -> str:
    data = json.loads(SOURCE.read_text())

    # --- Operators ---
    operators: dict[str, dict] = {}
    skipped_syntactic = 0
    for row in data["Operators"]:
        signature = row["运算符"].strip()
        name = parse_op_name(signature)
        if name is None or name in SYNTACTIC_ONLY_OP_NAMES:
            skipped_syntactic += 1
            continue
        category = row["类别"].strip()
        description = row["说明"].strip()
        if name in operators:
            continue  # dedupe: first occurrence wins
        operators[name] = {
            "category": category,
            "signature": signature,
            "description": description,
            "implemented": name in IMPLEMENTED_OPERATORS,
        }

    # --- Operands ---
    operands: dict[str, dict] = {}
    for cat in B_PLUS_CATEGORIES:
        for row in data[cat]:
            field = row["字段名"].strip()
            if cat == "Model" and field.startswith(MODEL_PROPRIETARY_PREFIX):
                continue
            operands[field] = {
                "category": cat,
                "subcategory": row["数据类别"].strip(),
                "dtype": row["类型"].strip(),
                "description": row["说明"].strip(),
                "data_source": DATA_SOURCE_BY_CATEGORY[cat],
            }

    # --- Render Python module ---
    lines: list[str] = []
    lines.append(dedent('''
        """Single source of truth for operators and operands in factor expressions.

        Generated by `scripts/build_brain_registry.py` from the Feishu/Lark
        Bitable export at `/tmp/brain_source_of_truth.json`.

        DO NOT EDIT BY HAND. Re-run the build script after any Bitable update.

        Scope (B+ expansion, 2026-04-18):
          - 57 named operators (+ 6 comparison / and / or / not handled by
            AST directly, totaling 66 BRAIN operators)
          - 28 operators implemented vectorized; remainder raise NotImplementedError
            at execute-time until promoted in a follow-up PR
          - 190 operands: PriceVolume 40 + Fundamental 58 + Model-derivable 35
                        + Analyst 40 + Sentiment 17
          - Excluded for future expansion: News, Options, SocialMedia, mdl77_*
        """

        from __future__ import annotations

        from dataclasses import dataclass


        @dataclass(frozen=True)
        class OperatorSpec:
            """Metadata for one operator in the factor grammar."""

            name: str
            category: str  # Arithmetic / Time Series / Cross Sectional / Logical / Group / Vector / Transformational
            signature: str  # BRAIN canonical signature, e.g., "ts_mean(x, d)"
            description: str
            implemented: bool  # True = has vectorized impl; False = registered, raises NotImplementedError


        @dataclass(frozen=True)
        class OperandSpec:
            """Metadata for one data field available as an operand in factor expressions."""

            name: str
            category: str  # PriceVolume / Fundamental / Model / Analyst / Sentiment
            subcategory: str  # BRAIN sub-category in Chinese (from source-of-truth)
            dtype: str  # Matrix / Vector
            description: str
            data_source: str  # yfinance / edgar / local_compute / finnhub

    ''').lstrip())

    # Operators dict
    lines.append("OPERATORS: dict[str, OperatorSpec] = {")
    for name in sorted(operators):
        m = operators[name]
        lines.append(
            f"    {py_repr(name)}: OperatorSpec("
            f"name={py_repr(name)}, "
            f"category={py_repr(m['category'])}, "
            f"signature={py_repr(m['signature'])}, "
            f"description={py_repr(m['description'])}, "
            f"implemented={m['implemented']}),"
        )
    lines.append("}")
    lines.append("")

    # Operands dict
    lines.append("OPERANDS: dict[str, OperandSpec] = {")
    for name in sorted(operands):
        m = operands[name]
        lines.append(
            f"    {py_repr(name)}: OperandSpec("
            f"name={py_repr(name)}, "
            f"category={py_repr(m['category'])}, "
            f"subcategory={py_repr(m['subcategory'])}, "
            f"dtype={py_repr(m['dtype'])}, "
            f"description={py_repr(m['description'])}, "
            f"data_source={py_repr(m['data_source'])}),"
        )
    lines.append("}")
    lines.append("")

    # Exported frozensets
    lines.append("OPERATOR_NAMES: frozenset[str] = frozenset(OPERATORS)")
    lines.append("OPERAND_NAMES: frozenset[str] = frozenset(OPERANDS)")
    lines.append(
        "IMPLEMENTED_OPERATOR_NAMES: frozenset[str] = frozenset("
        "n for n, s in OPERATORS.items() if s.implemented"
        ")"
    )
    lines.append("")

    # Counts sanity check
    lines.append(
        f"# Build-time counts (asserts caught drift if source-of-truth shape changes):\n"
        f"assert len(OPERATORS) == {len(operators)}, "
        f"f'expected {len(operators)} operators, got {{len(OPERATORS)}}'"
    )
    lines.append(
        f"assert len(OPERANDS) == {len(operands)}, "
        f"f'expected {len(operands)} operands, got {{len(OPERANDS)}}'"
    )
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    import subprocess
    import sys

    src = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(src)
    print(f"wrote {OUT}")

    # Sanity verify via subprocess (avoids importlib dataclass quirk)
    verify = subprocess.run(
        [sys.executable, "-c", (
            "import sys; "
            f"sys.path.insert(0, {str(OUT.parent.parent)!r}); "
            "from alpha_agent.core import brain_registry as r; "
            "by_cat = {}; "
            "from collections import Counter; "
            "by_cat = Counter(s.category for s in r.OPERANDS.values()); "
            "print(f'  operators:  {len(r.OPERATORS)} total, "
            "{len(r.IMPLEMENTED_OPERATOR_NAMES)} implemented'); "
            "print(f'  operands:   {len(r.OPERANDS)} total'); "
            "[print(f'    {c}: {n}') for c, n in sorted(by_cat.items())]"
        )],
        capture_output=True, text=True,
    )
    print(verify.stdout, end="")
    if verify.returncode != 0:
        print(verify.stderr, file=sys.stderr)
        raise SystemExit(verify.returncode)
